<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>scopeName</key>
    <string>source.slice</string>
    <key>name</key>
    <string>Slice</string>
    <key>fileTypes</key>
    <array>
      <string>ice</string>
    </array>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#comments</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#metadata</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(bool|byte|class|dictionary|double|enum|exception|float|int|interface|LocalObject|long|Object|Value|sequence|short|string|struct|void)\b</string>
        <key>name</key>
        <string>storage.type.slice</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(module)\b</string>
        <key>name</key>
        <string>keyword.control.namespace.slice</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(const|extends|implements|optional|out)\b</string>
        <key>name</key>
        <string>storage.modifier.slice</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(idempotent|throws)\b</string>
        <key>name</key>
        <string>keyword.control.slice</string>
      </dict>
      <dict>
        <key>begin</key>
        <string>^\s*(#)\s*(define|ifdef|ifndef|pragma|endif)\b</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.keyword.slice</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control.import.slice</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?=(?://|/\*))|(?&lt;!\\)(?=\n)</string>
        <key>name</key>
        <string>meta.preprocessor.slice</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(?&gt;\\\s*\n)</string>
            <key>name</key>
            <string>punctuation.separator.continuation.slice</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>^\s*(#)\s*(include)\b\s+</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.keyword.slice</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control.include.slice</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?=(?://|/\*))|(?&lt;!\\)(?=\n)</string>
        <key>name</key>
        <string>meta.preprocessor.include.slice</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(?&gt;\\\s*\n)</string>
            <key>name</key>
            <string>punctuation.separator.continuation.slice</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>"</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.slice</string>
              </dict>
            </dict>
            <key>end</key>
            <string>"</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.slice</string>
              </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.double.include.slice</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>&lt;</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.slice</string>
              </dict>
            </dict>
            <key>end</key>
            <string>&gt;</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.slice</string>
              </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.other.lt-gt.include.slice</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>match</key>
        <string>::</string>
        <key>name</key>
        <string>punctuation.separator.namespace.access.slice</string>
      </dict>
      <dict>
        <key>match</key>
        <string>\b(true|false)\b</string>
        <key>name</key>
        <string>constant.language.slice</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#strings</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>comments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>meta.toc-list.banner.block.slice</string>
              </dict>
            </dict>
            <key>match</key>
            <string>^/\* =(\s*.*?)\s*= \*/$\n?</string>
            <key>name</key>
            <string>comment.block.slice</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>/\*</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.begin.slice</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\*/</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.end.slice</string>
              </dict>
            </dict>
            <key>name</key>
            <string>comment.block.slice</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\*/.*\n</string>
            <key>name</key>
            <string>invalid.illegal.stray-comment-end.slice</string>
          </dict>
          <dict>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>meta.toc-list.banner.line.slice</string>
              </dict>
            </dict>
            <key>match</key>
            <string>^// =(\s*.*?)\s*=\s*$\n?</string>
            <key>name</key>
            <string>comment.line.banner.slice</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>(^[ \t]+)?(?=//)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.whitespace.comment.leading.slice</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?!\G)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>//</string>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.comment.slice</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>\n</string>
                <key>name</key>
                <string>comment.line.double-slash.slice</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>match</key>
                    <string>(?&gt;\\\s*\n)</string>
                    <key>name</key>
                    <string>punctuation.separator.continuation.slice</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>metadata</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\[</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.metadata.begin.slice</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\]</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.metadata.end.slice</string>
              </dict>
            </dict>
            <key>name</key>
            <string>support.function.metadata.slice</string>
          </dict>
        </array>
      </dict>
      <key>strings</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>"</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.slice</string>
              </dict>
            </dict>
            <key>end</key>
            <string>"</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.slice</string>
              </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.double.slice</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#string_escaped_char</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#string_placeholder</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#line_continuation_character</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>'</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.slice</string>
              </dict>
            </dict>
            <key>end</key>
            <string>'</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.slice</string>
              </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.single.slice</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#string_escaped_char</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#line_continuation_character</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
    </dict>
  </dict>
</plist>
